/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ChatRouteImport } from "./routes/chat";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ChatIndexRouteImport } from "./routes/chat.index";
import { Route as ChatSessionIdRouteImport } from "./routes/chat.$sessionId";
import { Route as ApiProxyRouteImport } from "./routes/api/proxy";
import { Route as ApiFeedbackRouteImport } from "./routes/api/feedback";
import { Route as ApiERouteImport } from "./routes/api/e";
import { Route as OwnerRepoIndexRouteImport } from "./routes/$owner.$repo.index";
import { Route as ApiGithubPublicRouteImport } from "./routes/api/github/public";
import { Route as ApiAutumnSplatRouteImport } from "./routes/api/autumn/$";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as OwnerRepoSplatRouteImport } from "./routes/$owner.$repo.$";

const ChatRoute = ChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ChatRoute,
} as any);
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: "/$sessionId",
  path: "/$sessionId",
  getParentRoute: () => ChatRoute,
} as any);
const ApiProxyRoute = ApiProxyRouteImport.update({
  id: "/api/proxy",
  path: "/api/proxy",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: "/api/feedback",
  path: "/api/feedback",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiERoute = ApiERouteImport.update({
  id: "/api/e",
  path: "/api/e",
  getParentRoute: () => rootRouteImport,
} as any);
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: "/$owner/$repo/",
  path: "/$owner/$repo/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiGithubPublicRoute = ApiGithubPublicRouteImport.update({
  id: "/api/github/public",
  path: "/api/github/public",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAutumnSplatRoute = ApiAutumnSplatRouteImport.update({
  id: "/api/autumn/$",
  path: "/api/autumn/$",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const OwnerRepoSplatRoute = OwnerRepoSplatRouteImport.update({
  id: "/$owner/$repo/$",
  path: "/$owner/$repo/$",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/chat": typeof ChatRouteWithChildren;
  "/api/e": typeof ApiERoute;
  "/api/feedback": typeof ApiFeedbackRoute;
  "/api/proxy": typeof ApiProxyRoute;
  "/chat/$sessionId": typeof ChatSessionIdRoute;
  "/chat/": typeof ChatIndexRoute;
  "/$owner/$repo/$": typeof OwnerRepoSplatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/autumn/$": typeof ApiAutumnSplatRoute;
  "/api/github/public": typeof ApiGithubPublicRoute;
  "/$owner/$repo/": typeof OwnerRepoIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/api/e": typeof ApiERoute;
  "/api/feedback": typeof ApiFeedbackRoute;
  "/api/proxy": typeof ApiProxyRoute;
  "/chat/$sessionId": typeof ChatSessionIdRoute;
  "/chat": typeof ChatIndexRoute;
  "/$owner/$repo/$": typeof OwnerRepoSplatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/autumn/$": typeof ApiAutumnSplatRoute;
  "/api/github/public": typeof ApiGithubPublicRoute;
  "/$owner/$repo": typeof OwnerRepoIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/chat": typeof ChatRouteWithChildren;
  "/api/e": typeof ApiERoute;
  "/api/feedback": typeof ApiFeedbackRoute;
  "/api/proxy": typeof ApiProxyRoute;
  "/chat/$sessionId": typeof ChatSessionIdRoute;
  "/chat/": typeof ChatIndexRoute;
  "/$owner/$repo/$": typeof OwnerRepoSplatRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/autumn/$": typeof ApiAutumnSplatRoute;
  "/api/github/public": typeof ApiGithubPublicRoute;
  "/$owner/$repo/": typeof OwnerRepoIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/chat"
    | "/api/e"
    | "/api/feedback"
    | "/api/proxy"
    | "/chat/$sessionId"
    | "/chat/"
    | "/$owner/$repo/$"
    | "/api/auth/$"
    | "/api/autumn/$"
    | "/api/github/public"
    | "/$owner/$repo/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/api/e"
    | "/api/feedback"
    | "/api/proxy"
    | "/chat/$sessionId"
    | "/chat"
    | "/$owner/$repo/$"
    | "/api/auth/$"
    | "/api/autumn/$"
    | "/api/github/public"
    | "/$owner/$repo";
  id:
    | "__root__"
    | "/"
    | "/chat"
    | "/api/e"
    | "/api/feedback"
    | "/api/proxy"
    | "/chat/$sessionId"
    | "/chat/"
    | "/$owner/$repo/$"
    | "/api/auth/$"
    | "/api/autumn/$"
    | "/api/github/public"
    | "/$owner/$repo/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ChatRoute: typeof ChatRouteWithChildren;
  ApiERoute: typeof ApiERoute;
  ApiFeedbackRoute: typeof ApiFeedbackRoute;
  ApiProxyRoute: typeof ApiProxyRoute;
  OwnerRepoSplatRoute: typeof OwnerRepoSplatRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiAutumnSplatRoute: typeof ApiAutumnSplatRoute;
  ApiGithubPublicRoute: typeof ApiGithubPublicRoute;
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/chat": {
      id: "/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof ChatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/chat/": {
      id: "/chat/";
      path: "/";
      fullPath: "/chat/";
      preLoaderRoute: typeof ChatIndexRouteImport;
      parentRoute: typeof ChatRoute;
    };
    "/chat/$sessionId": {
      id: "/chat/$sessionId";
      path: "/$sessionId";
      fullPath: "/chat/$sessionId";
      preLoaderRoute: typeof ChatSessionIdRouteImport;
      parentRoute: typeof ChatRoute;
    };
    "/api/proxy": {
      id: "/api/proxy";
      path: "/api/proxy";
      fullPath: "/api/proxy";
      preLoaderRoute: typeof ApiProxyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/feedback": {
      id: "/api/feedback";
      path: "/api/feedback";
      fullPath: "/api/feedback";
      preLoaderRoute: typeof ApiFeedbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/e": {
      id: "/api/e";
      path: "/api/e";
      fullPath: "/api/e";
      preLoaderRoute: typeof ApiERouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$owner/$repo/": {
      id: "/$owner/$repo/";
      path: "/$owner/$repo";
      fullPath: "/$owner/$repo/";
      preLoaderRoute: typeof OwnerRepoIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/github/public": {
      id: "/api/github/public";
      path: "/api/github/public";
      fullPath: "/api/github/public";
      preLoaderRoute: typeof ApiGithubPublicRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/autumn/$": {
      id: "/api/autumn/$";
      path: "/api/autumn/$";
      fullPath: "/api/autumn/$";
      preLoaderRoute: typeof ApiAutumnSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$owner/$repo/$": {
      id: "/$owner/$repo/$";
      path: "/$owner/$repo/$";
      fullPath: "/$owner/$repo/$";
      preLoaderRoute: typeof OwnerRepoSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface ChatRouteChildren {
  ChatSessionIdRoute: typeof ChatSessionIdRoute;
  ChatIndexRoute: typeof ChatIndexRoute;
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatSessionIdRoute: ChatSessionIdRoute,
  ChatIndexRoute: ChatIndexRoute,
};

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  ApiERoute: ApiERoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  ApiProxyRoute: ApiProxyRoute,
  OwnerRepoSplatRoute: OwnerRepoSplatRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAutumnSplatRoute: ApiAutumnSplatRoute,
  ApiGithubPublicRoute: ApiGithubPublicRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
