/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatSessionIdRouteImport } from './routes/chat.$sessionId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner.$repo.index'
import { Route as OwnerRepoSplatRouteImport } from './routes/$owner.$repo.$'

const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSessionIdRoute = ChatSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => ChatRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoSplatRoute = OwnerRepoSplatRouteImport.update({
  id: '/$owner/$repo/$',
  path: '/$owner/$repo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/chat/': typeof ChatIndexRoute
  '/$owner/$repo/$': typeof OwnerRepoSplatRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/chat': typeof ChatIndexRoute
  '/$owner/$repo/$': typeof OwnerRepoSplatRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$sessionId': typeof ChatSessionIdRoute
  '/chat/': typeof ChatIndexRoute
  '/$owner/$repo/$': typeof OwnerRepoSplatRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/auth/callback'
    | '/chat/$sessionId'
    | '/chat/'
    | '/$owner/$repo/$'
    | '/$owner/$repo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/callback'
    | '/chat/$sessionId'
    | '/chat'
    | '/$owner/$repo/$'
    | '/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/auth/callback'
    | '/chat/$sessionId'
    | '/chat/'
    | '/$owner/$repo/$'
    | '/$owner/$repo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  OwnerRepoSplatRoute: typeof OwnerRepoSplatRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$sessionId': {
      id: '/chat/$sessionId'
      path: '/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof ChatSessionIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/$': {
      id: '/$owner/$repo/$'
      path: '/$owner/$repo/$'
      fullPath: '/$owner/$repo/$'
      preLoaderRoute: typeof OwnerRepoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatSessionIdRoute: typeof ChatSessionIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatSessionIdRoute: ChatSessionIdRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  OwnerRepoSplatRoute: OwnerRepoSplatRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
